name: build-and-test

on:
    push:
        branches:
            - master

permissions: read-all

jobs:
    build-and-test:
        name: ${{ matrix.toolchain }}
        runs-on: ${{ matrix.os }}
        
        strategy:
            fail-fast: false
            matrix:
                platform: [ x64 ]
                # os: [ ubuntu-latest, windows-latest, macos-latest ] # ubuntu use gcc9, macos apple-clang seems has some bugs
                os: [ windows-latest ]
                configuration: [ Debug, Release, MinSizeRel, RelWithDebInfo ]
                exclude:
                    -   os: windows-latest
                        configuration: [ Release, MinSizeRel, RelWithDebInfo ] # command line error D8016: '/O2' and '/RTC1' command-line options are incompatible
        
        steps:
            -   name: Checkout Code
                uses: actions/checkout@v2
                with:
                    submodules: true
            
            -   name: Configure (${{ matrix.configuration }})
                run: cmake -S . -Bbuild -DCMAKE_BUILD_TYPE=${{ matrix.configuration }}
            
            -   name: Build with ${{ matrix.compiler }}
                run: cmake --build build
            
            -   name: Build and run test
                working-directory: build
                env:
                    CTEST_OUTPUT_ON_FAILURE: 1
                run: ctest -C ${{ matrix.configuration }}
